[agent]
  interval = "15s"
  flush_interval = "15s"

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  container_name_include = ["*openchain-production-*"]
  total_include = ["cpu"]
  timeout = "5s"

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 1
  collectors_exclude = ["gocollector", "process"]
