FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN go mod init openchain-trueblocks && go get github.com/google/uuid

COPY infra/trueblocks/main.go .

RUN CGO_ENABLED=0 GOOS=linux go build -o trueblocks main.go

FROM alpine:latest

WORKDIR /app
COPY --from=builder /app/trueblocks .

EXPOSE 8080

CMD ["./trueblocks"]
