FROM node:20.19-alpine3.21 AS builder

WORKDIR /app
RUN npm install -g pnpm@9.15.0

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
COPY packages/proto ./packages/proto
COPY apps/web ./apps/web

RUN pnpm install --frozen-lockfile
RUN pnpm --filter @openchain/web build

FROM node:20.19-alpine3.21
WORKDIR /app/apps/web
ENV NODE_ENV=production
COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/apps/web/node_modules ./node_modules
COPY --from=builder /app/apps/web/dist ./dist
USER node
EXPOSE 3000
CMD ["node", "/app/node_modules/.pnpm/srvx@0.11.22/node_modules/srvx/bin/srvx.mjs", "serve", "--prod", "--static=/app/apps/web/dist/client", "--entry=./dist/server/server.js"]
