-- Database Schema for OpenChain Platform

CREATE TABLE IF NOT EXISTS addresses (
    address VARCHAR(66) PRIMARY KEY,
    network VARCHAR(32) NOT NULL DEFAULT 'ETHEREUM_SEPOLIA',
    is_contract BOOLEAN NOT NULL DEFAULT FALSE,
    entity_type VARCHAR(32) NOT NULL DEFAULT 'EOA',
    label VARCHAR(255) NOT NULL DEFAULT '',
    balance_wei VARCHAR(78) NOT NULL DEFAULT '0',
    tx_count BIGINT NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMP WITH TIME ZONE,
    last_seen_at TIMESTAMP WITH TIME ZONE,
    total_received_wei VARCHAR(78) NOT NULL DEFAULT '0',
    total_sent_wei VARCHAR(78) NOT NULL DEFAULT '0',
    risk_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    hash VARCHAR(66) PRIMARY KEY,
    network VARCHAR(32) NOT NULL DEFAULT 'ETHEREUM_SEPOLIA',
    block_number BIGINT NOT NULL,
    block_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    from_address VARCHAR(66) NOT NULL REFERENCES addresses(address),
    to_address VARCHAR(66) NOT NULL,
    value_wei VARCHAR(78) NOT NULL DEFAULT '0',
    gas_used VARCHAR(32) NOT NULL DEFAULT '0',
    gas_price_wei VARCHAR(78) NOT NULL DEFAULT '0',
    is_contract_creation BOOLEAN NOT NULL DEFAULT FALSE,
    status_success BOOLEAN NOT NULL DEFAULT TRUE,
    input_data TEXT,
    method_name VARCHAR(128) NOT NULL DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_tx_from ON transactions(from_address);
CREATE INDEX IF NOT EXISTS idx_tx_to ON transactions(to_address);
CREATE INDEX IF NOT EXISTS idx_tx_block ON transactions(block_number);

CREATE TABLE IF NOT EXISTS token_transfers (
    id BIGSERIAL PRIMARY KEY,
    tx_hash VARCHAR(66) NOT NULL REFERENCES transactions(hash),
    log_index INT NOT NULL,
    network VARCHAR(32) NOT NULL DEFAULT 'ETHEREUM_SEPOLIA',
    token_address VARCHAR(66) NOT NULL,
    symbol VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
    decimals INT NOT NULL DEFAULT 18,
    from_address VARCHAR(66) NOT NULL,
    to_address VARCHAR(66) NOT NULL,
    raw_value VARCHAR(78) NOT NULL DEFAULT '0',
    block_number BIGINT NOT NULL,
    block_timestamp TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_token_tx ON token_transfers(tx_hash);
CREATE INDEX IF NOT EXISTS idx_token_from ON token_transfers(from_address);
CREATE INDEX IF NOT EXISTS idx_token_to ON token_transfers(to_address);

CREATE TABLE IF NOT EXISTS labels (
    id VARCHAR(64) PRIMARY KEY,
    address VARCHAR(66) NOT NULL REFERENCES addresses(address),
    network VARCHAR(32) NOT NULL DEFAULT 'ETHEREUM_SEPOLIA',
    category VARCHAR(64) NOT NULL,
    label VARCHAR(255) NOT NULL,
    confidence DOUBLE PRECISION NOT NULL DEFAULT 1.0,
    evidence_url TEXT NOT NULL DEFAULT '',
    source VARCHAR(128) NOT NULL DEFAULT 'COMMUNITY',
    created_by VARCHAR(128) NOT NULL DEFAULT 'SYSTEM',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_labels_addr ON labels(address);

CREATE TABLE IF NOT EXISTS risk_evaluations (
    id BIGSERIAL PRIMARY KEY,
    address VARCHAR(66) NOT NULL REFERENCES addresses(address),
    network VARCHAR(32) NOT NULL DEFAULT 'ETHEREUM_SEPOLIA',
    total_score DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    risk_level VARCHAR(32) NOT NULL DEFAULT 'LOW',
    flags_json JSONB NOT NULL DEFAULT '[]'::jsonb,
    evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_risk_addr ON risk_evaluations(address);

CREATE TABLE IF NOT EXISTS cases (
    id VARCHAR(64) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    tags JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_by VARCHAR(128) NOT NULL DEFAULT 'ANALYST',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS case_nodes (
    id BIGSERIAL PRIMARY KEY,
    case_id VARCHAR(64) NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    address VARCHAR(66) NOT NULL,
    label VARCHAR(255) NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS case_edges (
    id BIGSERIAL PRIMARY KEY,
    case_id VARCHAR(64) NOT NULL REFERENCES cases(id) ON DELETE CASCADE,
    source_address VARCHAR(66) NOT NULL,
    target_address VARCHAR(66) NOT NULL,
    tx_hash VARCHAR(66) NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS watchlists (
    id VARCHAR(64) PRIMARY KEY,
    user_id VARCHAR(128) NOT NULL,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(66) NOT NULL,
    network VARCHAR(32) NOT NULL DEFAULT 'ETHEREUM_SEPOLIA',
    notify_email BOOLEAN NOT NULL DEFAULT TRUE,
    notify_websocket BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
